---
- hosts: localhost
  gather_facts: no
  connection: local

  tasks:
          - name: Register uptime command.
            command: uptime
            register: system_uptime

          - name: Print registered output.
            debug: 
                var: system_uptime.stdout

          - name: Print if command result change.
            debug:
                msg: "command changed"
            when: system_uptime is changed 
