---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerleenguy/docker-centos:8-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
