---
- name: Intall Apache.
  hosts: iperftest

  tasks:
    - name: Install Apache.
      apt:
        name:
          - apache2
          - apache2-dev
        state: present
    - name: Copy config files.
      copy:
        src: "{{ item.src }}" # ansible with_items create a item variable item.src access to src into with_items
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - src: /etc/apache2/apache2.conf
          dest: /etc/apache2/apache2.conf
        - src: apache2-vhost.conf
          dest: /etc/apache2/apache2-vhosts.conf
    
    - name: Start and enable apache2
      service:
        name: apache2
        state: started
        enabled: true
