---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
          # - name: Register uptime command.
          #  command: uptime
          #  register: system_uptime

          # sintax check will pass wheter or not this file exists.
          - include_tasks: dates.yml

          # this will cause a failure, since it can be checked statically
          - import_tasks: free.yml

          - name: Print debug output.
            debug:
                    msg: "Hello error"
