---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
          - name: Register uptime command.
            command: uptime
            changed_when: false
            register: system_uptime

          - name: Print registered output.
            debug:
                    var: system_uptime.stdout
