---
# run with ansible-playbook main.yml -K
- hosts: localhost
  connections: local

  vars: 
        homebrew_installed_pagackages:
          - pv
  roles:
          - elliotweiser.osx-command-line-tools
          - role: geerlinguy.homebrew
            become: yes
